# This is a basic workflow to help you get started with Actions

name: Docker Image Transfer

# Controls when the action will run. 
on:
  issues:
    types: [opened, edited]

jobs:
  ffdit:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.issue.title, 'ffdit') }}
    permissions:
      issues: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: print github event
        run: |
          cat << EOF > proposal.json
          ${{ github.event.issue.body }}
          EOF
      - name: startup ffdit 
        run: ./startup -f proposal.json
